Monologue.sidebar              = ["latest_posts", "latest_tweets"]   # this will add the latests posts and latests tweets in the right sidebar.
Monologue.show_rss_icon        = true # will show the RSS icon (with link) in the header)
Monologue.facebook_url         = "https://www.facebook.com/pages/Vegan-BFFs/352755424834915" # if set, this will enable Facebook icon and link it to your Facebook page.
#Monologue.google_plus_account_url = # if set, this will enable Google+ icon and link it to that URL.
#Monologue.linkedin_url         =  # if set, will enable Linked In icon and link to this URL.
Monologue.github_username      = "http://github.com/kellimohr"  # if set, will enable Github icon and link to this URL.
Monologue.gauge_analytics_site_id = "" # add your [Gaug.es](http://get.gaug.es/) id here to enable it.
Monologue.facebook_logo           = 'facebook_64.png'  # used in the open graph protocol to display an image when a post is liked
Monologue.site_name            = "Vegan BFFs"
Monologue.site_subtitle        = "So Veggie-licious!"
Monologue.site_url             = "www.veganbffs.com"
Monologue.disqus_shortname     = "" # register on disqus.com if you don't have one
Monologue.meta_description     = "Vegan BFFs Blog"
Monologue.meta_keyword         = "vegan, BFFs, community"
Monologue.twitter_username     = ""
Monologue.twitter_locale       = "en" # This is the locale for twitter. "en" for english or "fr" for french. There is much more!
Monologue.facebook_like_locale = "en_US" # same, but for facebook. French is "fr_CA"
Monologue.google_plusone_locale = "en" # same for Google +
Monologue.admin_force_ssl       = true # that can be set to false if you don't have SSL, but it is not recommended
Monologue.posts_per_page      = 5 # OPTIONAL: number of posts per page on main page. It defaults to 10 currently
Monologue.google_analytics_id  = "" # OPTIONAL: Your Google Analytics code should be here if you have one.